name: Docker Builder

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
        
    - name: Build the Docker image and push
      env:
        HUB_NAME: ${{ secrets.DOCKER_NAME }}
        HUB_KEY: ${{ secrets.DOCKER_TOKEN }}
      run: |
        docker login -u $HUB_NAME -p $HUB_KEY

        docker build . --pull --no-cache -f Dockerfile -t zocker160/sheepit-docker-webui:latest
        docker build . --pull --no-cache -f Dockerfile.nvidia-legacy -t zocker160/sheepit-docker-webui:nvidia-legacy

        docker tag zocker160/sheepit-docker-webui:latest zocker160/sheepit-docker-webui:nvidia
        
        docker push zocker160/sheepit-docker-webui:latest
        docker push zocker160/sheepit-docker-webui:nvidia
        docker push zocker160/sheepit-docker-webui:nvidia-legacy
